### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by qsniyg** [WeCase/WeCase#161]
I tried to login using different user accounts, but none of them worked.

The error is `Invalid Application() or wrong username/password.`

**Comment by biergaizi** [comment]
What version did you use? Did you use the latest version from dev-0.06 branch? If you did, then that means our API Key is expired, since this project has been suspended, no one maintains it any more. Also, more restrictions for OpenAPI has been added, and current program is basically unusable without a major rewrite.

**Comment by qsniyg** [comment]
Yes, latest.

I had the same issue with my own project, using rpweibo (and a new API Key).

**Comment by biergaizi** [comment]
Okay, you should have reported it to rpweibo, I'll report this one for you. rpweibo is still maintained by me.

It looks like that Sina implemented unknown security restrictions on Sina API. Although I have reverse engineered the login mechanism, sometimes it has other paths different from normal login, for examples: new accounts, unusual IP geolocation, or a CAPTCHA is required.

I may have a look of this issue later.

**Comment by biergaizi** [comment]
Probably a CAPTCHA is required. Working on it.

**Comment by biergaizi** [comment]
Probably a CAPTCHA is required. Working on it.

**Comment by biergaizi** [comment]
@qsniyg 

Hello, are you still here? I think this problem occurs because you didn't not authorize your application to access your account, thus the automatic login doesn't work. The automatic login only works if your application has authorized before.

You may try to use `rpweibo.ManualAutheticator` and `REDIR = "https://api.weibo.com/oauth2/default.html"` at first, then open your web browser to copy

```
https://api.weibo.com/oauth2/default.html?code=[COPY THIS]
```

Once authorized, there will be no problem afterwards.

**Comment by qsniyg** [comment]
Sorry for replying so late! I don't log in here very often.

I just tried the new code, and wecase still appears to not log in. However, as you say, authenticating via ManualAutheticator works just fine :)
